# Generated by Django 5.1.5 on 2026-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='moq_per_size',
            field=models.PositiveIntegerField(blank=True, help_text='MOQ por talla individual (Agent-A H4)', null=True),
        ),
    ]
