# Generated by Django 5.2.11 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mwtuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwtuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
