# Generated by Django 5.2.11 on 2026-03-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('users', '0004_mwtuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwtuser',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='brands.brand'),
        ),
    ]
