# Generated by Django 5.1.5 on 2026-03-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
        ('brands', '0002_brandconfigversion_catalogversion'),
        ('clientes', '0002_clientgroup_clientultimateparent_clientsubsidiary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('content_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('agreement_resolution_level', models.CharField(blank=True, choices=[('subsidiary', 'Subsidiary'), ('group', 'Group'), ('brand_default', 'Brand Default')], max_length=20, null=True)),
                ('resolved_max_revisions', models.IntegerField(default=0)),
                ('revision_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('resolved_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agreements.brandclientagreement')),
            ],
            options={
                'db_table': 'orders_clientorder',
            },
        ),
        migrations.CreateModel(
            name='ClientOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('resolved_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('base_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('commission_applied', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('price_index_applied', models.DecimalField(decimal_places=6, default=1, max_digits=8)),
                ('override_mode', models.CharField(choices=[('none', 'None'), ('base_override', 'Base Override'), ('final_override_manual', 'Final Override Manual')], default='none', max_length=30)),
                ('is_formula_locked', models.BooleanField(default=False)),
                ('manual_override_reason', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.clientorder')),
            ],
            options={
                'db_table': 'orders_clientorderline',
            },
        ),
        migrations.CreateModel(
            name='ClientOrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload_canonical_version', models.IntegerField(default=1)),
                ('ceo_override_diff', models.JSONField(default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='orders.clientorder')),
            ],
            options={
                'db_table': 'orders_clientordersnapshot',
            },
        ),
    ]
