# Generated by Django 5.1.5 on 2026-03-04 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0004_alter_eventlog_aggregate_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidation_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('period', models.CharField(max_length=7)),
                ('brand', models.CharField(default='marluvas', max_length=50)),
                ('source_file', models.FileField(upload_to='liquidations/uploads/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('reconciled', 'Reconciled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('total_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_liquidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'liquidations_liquidation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiquidationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marluvas_reference', models.CharField(max_length=200)),
                ('concept', models.CharField(choices=[('comision', 'Comisión'), ('premio', 'Premio'), ('ajuste', 'Ajuste'), ('otro', 'Otro')], max_length=20)),
                ('client_payment_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_pct_reported', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_partial_payment', models.BooleanField(default=False)),
                ('commission_pct_expected', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('discrepancy', 'Discrepancy'), ('unmatched', 'Unmatched'), ('no_match_needed', 'No Match Needed')], default='unmatched', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='liquidations.liquidation')),
                ('matched_expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidation_matches', to='expedientes.expediente')),
                ('matched_proforma', models.ForeignKey(blank=True, limit_choices_to={'artifact_type': 'ART-02'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidation_matches', to='expedientes.artifactinstance')),
            ],
            options={
                'db_table': 'liquidations_liquidationline',
            },
        ),
    ]
