# Generated by Django 5.2.11 on 2026-03-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidation',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='liquidations/uploads/'),
        ),
        migrations.AlterField(
            model_name='liquidationline',
            name='client_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
