# Generated by Django 5.1.5 on 2026-02-28 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(choices=[('MARLUVAS', 'Marluvas')], default='MARLUVAS', max_length=20)),
                ('status', models.CharField(choices=[('REGISTRO', 'Registro'), ('PRODUCCION', 'Producción'), ('PREPARACION', 'Preparación'), ('DESPACHO', 'Despacho'), ('TRANSITO', 'Tránsito'), ('EN_DESTINO', 'En Destino'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='REGISTRO', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by_type', models.CharField(blank=True, choices=[('CEO', 'CEO'), ('SYSTEM', 'System')], max_length=10, null=True)),
                ('blocked_by_id', models.CharField(blank=True, help_text='user_id if CEO, rule_name if SYSTEM', max_length=255, null=True)),
                ('mode', models.CharField(blank=True, help_text='Modalidad operativa', max_length=50)),
                ('freight_mode', models.CharField(blank=True, max_length=50)),
                ('transport_mode', models.CharField(blank=True, max_length=50)),
                ('dispatch_mode', models.CharField(choices=[('MWT', 'MWT'), ('CLIENT', 'Client')], default='MWT', max_length=10)),
                ('price_basis', models.CharField(blank=True, max_length=50)),
                ('credit_clock_start_rule', models.CharField(choices=[('ON_CREATION', 'On Creation'), ('ON_SHIPMENT', 'On Shipment')], default='ON_CREATION', max_length=20)),
                ('credit_clock_started_at', models.DateTimeField(blank=True, default=None, help_text='Timestamp when credit clock started (FIX-7)', null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment_registered_at', models.DateTimeField(blank=True, null=True)),
                ('payment_registered_by_type', models.CharField(blank=True, choices=[('CEO', 'CEO'), ('SYSTEM', 'System')], max_length=10, null=True)),
                ('payment_registered_by_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_id', models.CharField(help_text='e.g. MWT-CR, SONDEL-CR', max_length=50, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2/3', max_length=3)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('DISTRIBUTOR', 'Distributor'), ('SUBDISTRIBUTOR', 'Sub-distributor'), ('THREEPL', '3PL'), ('FACTORY', 'Factory')], max_length=20)),
                ('relationship_to_mwt', models.CharField(choices=[('SELF', 'Self'), ('FRANCHISE', 'Franchise'), ('DISTRIBUTION', 'Distribution'), ('SERVICE', 'Service')], max_length=20)),
                ('frontend', models.CharField(choices=[('MWT_ONE', 'MWT.ONE'), ('PORTAL_MWT_ONE', 'Portal MWT.ONE'), ('EXTERNAL', 'External')], max_length=20)),
                ('visibility_level', models.CharField(choices=[('FULL', 'Full'), ('PARTNER', 'Partner'), ('LIMITED', 'Limited')], max_length=20)),
                ('pricing_visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('CLIENT', 'Client'), ('NONE', 'None')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ONBOARDING', 'Onboarding'), ('INACTIVE', 'Inactive')], default='ONBOARDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='e.g. "expediente.state_changed"', max_length=100)),
                ('aggregate_type', models.CharField(choices=[('EXPEDIENTE', 'Expediente'), ('TRANSFER', 'Transfer'), ('NODE', 'Node'), ('ARTIFACT', 'Artifact')], max_length=20)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('emitted_by', models.CharField(help_text='e.g. "C5:RegisterSAPConfirmation"', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, help_text='null until dispatcher consumes', null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('correlation_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['aggregate_type', 'aggregate_id'], name='idx_eventlog_aggregate'), models.Index(fields=['processed_at'], name='idx_eventlog_processed'), models.Index(fields=['correlation_id'], name='idx_eventlog_correlation')],
            },
        ),
        migrations.CreateModel(
            name='CostLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(help_text='ISO 4217', max_length=3)),
                ('phase', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_lines', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Cost Line',
                'verbose_name_plural': 'Cost Lines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(help_text='ART-01 to ART-12', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded'), ('VOID', 'Void')], default='DRAFT', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes_set', to='expedientes.artifactinstance')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_set', to='expedientes.artifactinstance')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Artifact Instance',
                'verbose_name_plural': 'Artifact Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='client',
            field=models.ForeignKey(help_text='Cliente', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_como_cliente', to='expedientes.legalentity'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='legal_entity',
            field=models.ForeignKey(help_text='Entidad emisora', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_emitidos', to='expedientes.legalentity'),
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(help_text='ISO 4217', max_length=3)),
                ('method', models.CharField(help_text='transferencia, cheque, otro', max_length=50)),
                ('reference', models.CharField(help_text='Número de comprobante', max_length=100)),
                ('registered_at', models.DateTimeField()),
                ('registered_by_type', models.CharField(choices=[('CEO', 'CEO'), ('SYSTEM', 'System')], max_length=10)),
                ('registered_by_id', models.CharField(max_length=255)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_lines', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Payment Line',
                'verbose_name_plural': 'Payment Lines',
                'ordering': ['-created_at'],
            },
        ),
    ]
