# Generated by Django 5.2.11 on 2026-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactinstance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('superseded', 'Superseded'), ('void', 'Void')], default='draft', max_length=20),
        ),
    ]
