# Generated by Django 5.2.11 on 2026-03-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_alter_artifactinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
