# Generated by Django 5.2.11 on 2026-03-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_alter_expediente_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='aggregate_type',
            field=models.CharField(choices=[('expediente', 'Expediente'), ('transfer', 'Transfer'), ('node', 'Node'), ('artifact', 'Artifact')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='blocked_by_type',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('system', 'System')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='payment_registered_by_type',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('system', 'System')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentline',
            name='registered_by_type',
            field=models.CharField(choices=[('ceo', 'CEO'), ('system', 'System')], max_length=10),
        ),
    ]
