# Generated by Django 5.2.11 on 2026-03-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_sprint5_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logisticsoption',
            name='mode',
            field=models.CharField(choices=[('aereo', 'Aéreo'), ('maritimo', 'Marítimo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsoption',
            name='source',
            field=models.CharField(choices=[('historical', 'Historical'), ('quote', 'Quote'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
