# Generated by Django 5.2.11 on 2026-03-06 04:01
# Modified: added dependency on brands.0004_seed_brands so MARLUVAS exists before FK is enforced

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_seed_brands'),
        ('expedientes', '0006_alter_logisticsoption_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='destination',
            field=models.CharField(choices=[('CR', 'Costa Rica'), ('USA', 'United States')], default='CR', max_length=10),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brands.brand'),
        ),
    ]
