# Generated by Django 5.2.11 on 2026-03-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_retarget_legalentity_fks_to_core'),
        ('transfers', '0002_retarget_legalentity_fks_to_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactinstance',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('SUPERSEDED', 'Superseded'), ('VOID', 'Void')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='costline',
            name='transfer',
            field=models.ForeignKey(blank=True, help_text='XOR with expediente – use one or the other', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_lines', to='transfers.transfer'),
        ),
        migrations.AlterField(
            model_name='costline',
            name='visibility',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('CLIENT', 'Client')], default='INTERNAL', help_text='internal=CEO-only, client=visible to client', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='aggregate_type',
            field=models.CharField(choices=[('EXPEDIENTE', 'Expediente'), ('TRANSFER', 'Transfer'), ('NODE', 'Node'), ('ARTIFACT', 'Artifact')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='blocked_by_type',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('SYSTEM', 'System')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_clock_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when credit clock started (FIX-7)', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='payment_registered_by_type',
            field=models.CharField(blank=True, choices=[('CEO', 'CEO'), ('SYSTEM', 'System')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='status',
            field=models.CharField(choices=[('REGISTRO', 'Registro'), ('PRODUCCION', 'Producción'), ('PREPARACION', 'Preparación'), ('DESPACHO', 'Despacho'), ('TRANSITO', 'Tránsito'), ('EN_DESTINO', 'En Destino'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='REGISTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsoption',
            name='mode',
            field=models.CharField(choices=[('AIR', 'Air'), ('SEA', 'Sea'), ('LAND', 'Land'), ('MULTIMODAL', 'Multimodal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logisticsoption',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentline',
            name='reference',
            field=models.CharField(help_text='Número de comprobante', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentline',
            name='registered_by_type',
            field=models.CharField(choices=[('CEO', 'CEO'), ('SYSTEM', 'System')], max_length=10),
        ),
    ]
