# Generated by Django 5.2.11 on 2026-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_alter_artifactinstance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costline',
            name='amount_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='H8 (USD)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='costline',
            name='base_currency',
            field=models.CharField(default='USD', help_text='H8', max_length=3),
        ),
        migrations.AddField(
            model_name='costline',
            name='behavior',
            field=models.CharField(choices=[('FIXED_PER_OPERATION', 'Fixed per Operation'), ('VARIABLE_PER_UNIT', 'Variable per Unit'), ('VARIABLE_PER_WEIGHT', 'Variable per Weight'), ('SEMI_VARIABLE', 'Semi-variable')], default='VARIABLE_PER_UNIT', help_text='H3', max_length=20),
        ),
        migrations.AddField(
            model_name='costline',
            name='category',
            field=models.CharField(choices=[('LANDED_COST', 'Landed Cost'), ('TAX_CREDIT', 'Tax Credit (IVA)'), ('RECOVERABLE', 'Recoverable'), ('NON_DEDUCTIBLE', 'Non-Deductible')], default='LANDED_COST', help_text='H2', max_length=20),
        ),
        migrations.AddField(
            model_name='costline',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='H8', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='aforo_date',
            field=models.DateField(blank=True, help_text='H9', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='aforo_type',
            field=models.CharField(blank=True, choices=[('VERDE', 'Verde (Levante Inmediato)'), ('AMARILLO', 'Amarillo (Revisión Documental)'), ('ROJO', 'Rojo (Revisión Física)')], help_text='H9', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='external_fiscal_refs',
            field=models.JSONField(blank=True, default=dict, help_text='DANFE, DU-E, etc. (H5)'),
        ),
    ]
