# Generated by Django 5.2.11 on 2026-03-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_expediente_nodo_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costline',
            name='behavior',
        ),
        migrations.RemoveField(
            model_name='costline',
            name='category',
        ),
        migrations.AddField(
            model_name='costline',
            name='cost_behavior',
            field=models.CharField(blank=True, choices=[('fixed_per_operation', 'Fixed per Operation'), ('variable_per_unit', 'Variable per Unit'), ('variable_per_weight', 'Variable per Weight'), ('semi_variable', 'Semi-Variable')], help_text='H3', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='costline',
            name='cost_category',
            field=models.CharField(choices=[('landed_cost', 'Landed Cost'), ('tax_credit', 'Tax Credit (recuperable)'), ('recoverable', 'Recoverable (otro)'), ('non_deductible', 'Non-Deductible')], default='landed_cost', help_text='H2', max_length=20),
        ),
        migrations.AlterField(
            model_name='costline',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='H8', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='aforo_type',
            field=models.CharField(blank=True, choices=[('verde', 'Verde (Levante Inmediato)'), ('amarillo', 'Amarillo (Revisión Documental)'), ('rojo', 'Rojo (Revisión Física)')], help_text='H9', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='external_fiscal_refs',
            field=models.JSONField(blank=True, default=list, help_text='DANFE, DU-E, etc. (H5)'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='status',
            field=models.CharField(choices=[('REGISTRO', 'Registro'), ('PRODUCCION', 'Producción'), ('PREPARACION', 'Preparación'), ('DESPACHO', 'Despacho'), ('TRANSITO', 'Tránsito'), ('EN_DESTINO', 'En Destino'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], db_index=True, default='REGISTRO', max_length=20),
        ),
    ]
