# Generated by Django 5.1.5 on 2026-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_remove_costline_behavior_remove_costline_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='snapshot_commercial',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of pricing, incoterms, payment terms, and agreements (S14-05)'),
        ),
    ]
