# Generated by Django 5.2.11 on 2026-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0014_expediente_snapshot_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='credit_blocked',
            field=models.BooleanField(default=False, help_text='Flag indicating if the expediente is currently blocked due to credit clock'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='credit_warning',
            field=models.BooleanField(default=False, help_text='Warning flag for credit threshold'),
        ),
    ]
