# Generated by Django 5.2.11 on 2026-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0015_expediente_credit_blocked_expediente_credit_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='reopen_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times reopened'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='reopen_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
