# Generated by Django 5.1.5 on 2026-03-27 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandconfigversion_catalogversion'),
        ('expedientes', '0017_sprint18_all'),
        ('pricing', '0002_pricelistitem_moq_per_size'),
        ('productos', '0003_productmaster_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='airline_or_shipping_company',
            field=models.CharField(blank=True, help_text='Nombre de la aerolinea o naviera utilizada', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='arrival_location',
            field=models.CharField(blank=True, help_text='Puerto o aeropuerto de llegada del envio', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='awb_bl_number',
            field=models.CharField(blank=True, help_text='Numero Air Waybill (aereo) o Bill of Lading (maritimo)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='credit_days_client',
            field=models.IntegerField(blank=True, help_text='Dias de credito acordados con el cliente', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='credit_days_mwt',
            field=models.IntegerField(blank=True, help_text='Dias de credito acordados con MWT', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='credit_limit_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del limite de credito del cliente al momento de creacion', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='credit_limit_mwt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del limite de credito MWT al momento de creacion', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='dispatch_additional_info',
            field=models.TextField(blank=True, help_text='Informacion adicional libre sobre el despacho', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fabrication_end_date',
            field=models.DateField(blank=True, help_text='Fecha de fin de fabricacion', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='fabrication_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de fabricacion', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='factory_order_number',
            field=models.CharField(blank=True, help_text='Numero de orden en sistema del fabricante. Campo flat para queries rapidos.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='intermediate_airport_or_port',
            field=models.CharField(blank=True, help_text='Aeropuerto o puerto de escala intermedia', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='invoice_client_number',
            field=models.CharField(blank=True, help_text='Numero de factura emitida al cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='invoice_mwt_number',
            field=models.CharField(blank=True, help_text='Numero de factura interna MWT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='master_expediente',
            field=models.ForeignKey(blank=True, help_text='Expediente master cuando este fue fusionado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_followers', to='expedientes.expediente'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='operado_por',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('MWT', 'Muito Work Limitada')], help_text='Quien opera logisticamente este expediente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='order_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total del pedido en moneda del expediente', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origin_location',
            field=models.CharField(blank=True, help_text='Puerto o aeropuerto de origen del envio', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='payment_date_dispatch',
            field=models.DateField(blank=True, help_text='Fecha en que se realiza el pago en el estado DESPACHO', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='payment_mode_shipping',
            field=models.CharField(blank=True, choices=[('PREPAGO', 'Prepago'), ('CONTRAENTREGA', 'Contraentrega')], help_text='Modalidad de pago del flete', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='proforma_client_number',
            field=models.CharField(blank=True, help_text='Numero de proforma emitida al cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='proforma_mwt_number',
            field=models.CharField(blank=True, help_text='Numero de proforma emitida a MWT', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Numero de orden de compra del cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='ref_number',
            field=models.CharField(blank=True, help_text='Numero de referencia interna del expediente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='shipment_date',
            field=models.DateField(blank=True, help_text='Fecha efectiva de despacho / embarque', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='shipping_method',
            field=models.CharField(blank=True, help_text='Metodo de envio (aereo, maritimo, terrestre, courier)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='shipping_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del flete de envio', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='Link clicable de tracking (DHL, FedEx, naviera, etc.)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='transit_arrival_date',
            field=models.DateField(blank=True, help_text='Fecha estimada o real de llegada en transito', null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_awb_bl',
            field=models.URLField(blank=True, help_text='URL del AWB o BL escaneado', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_certificado_origen',
            field=models.URLField(blank=True, help_text='URL del certificado de origen', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_cotizacion_envio',
            field=models.URLField(blank=True, help_text='URL de la cotizacion de envio', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_factura_cliente',
            field=models.URLField(blank=True, help_text='URL de la factura del cliente', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_factura_muito_work',
            field=models.URLField(blank=True, help_text='URL de la factura interna MWT', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_list_empaque',
            field=models.URLField(blank=True, help_text='URL del documento lista de empaque', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_orden_compra',
            field=models.URLField(blank=True, help_text='URL del documento de orden de compra', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_packing_list_detallado',
            field=models.URLField(blank=True, help_text='URL del packing list detallado para aduana', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_proforma_cliente',
            field=models.URLField(blank=True, help_text='URL del documento de proforma del cliente', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='url_proforma_muito_work',
            field=models.URLField(blank=True, help_text='URL del documento de proforma MWT', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cargo_manager',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('FABRICA', 'Fabrica')], help_text='Quien gestiona la carga y envio', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_exposure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exposure calculado = total_lines - total_pagos_confirmados', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_released',
            field=models.BooleanField(default=False, help_text='True cuando credit_exposure <= 0. SOLO lo setea recalculate_expediente_credit().'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('EXW', 'Ex Works'), ('FOB', 'Free On Board'), ('CIF', 'Cost, Insurance and Freight'), ('DDP', 'Delivered Duty Paid')], help_text='Incoterm pactado (Sprint 18)', max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ExpedientePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('COMPLETO', 'Pago Completo'), ('PARCIAL', 'Pago Parcial')], help_text='Tipo de pago registrado', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('NOTA_CREDITO', 'Nota de Credito')], help_text='Metodo de pago utilizado', max_length=30)),
                ('payment_date', models.DateField(help_text='Fecha efectiva del pago')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Monto pagado en la moneda del expediente', max_digits=12)),
                ('additional_info', models.TextField(blank=True, help_text='Informacion adicional libre sobre el pago', null=True)),
                ('url_comprobante', models.URLField(blank=True, help_text='URL del comprobante de pago', max_length=500, null=True)),
                ('credit_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Estado de confirmacion del pago para liberacion de credito', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Expediente Pago',
                'verbose_name_plural': 'Expediente Pagos',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='FactoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Numero en sistema del fabricante', max_length=100)),
                ('proforma_client_number', models.CharField(blank=True, max_length=100, null=True)),
                ('proforma_mwt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_number', models.CharField(blank=True, help_text='Numero de orden de compra al fabricante', max_length=100, null=True)),
                ('url_proforma_client', models.URLField(blank=True, max_length=500, null=True)),
                ('url_proforma_mwt', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_orders', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Factory Order',
                'verbose_name_plural': 'Factory Orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad original pedida')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario editable por expediente.', max_digits=12)),
                ('price_source', models.CharField(choices=[('pricelist', 'Lista de precios activa'), ('manual', 'Ingresado manualmente'), ('override', 'Override por expediente')], default='manual', help_text='Origen del precio', max_length=30)),
                ('quantity_modified', models.PositiveIntegerField(blank=True, help_text='Cantidad modificada post-creacion (si aplica)', null=True)),
                ('unit_price_modified', models.DecimalField(blank=True, decimal_places=2, help_text='Precio modificado post-creacion (si aplica)', max_digits=12, null=True)),
                ('modification_reason', models.CharField(blank=True, help_text='Razon del cambio de cantidad o precio', max_length=200, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del precio base de la lista de precios', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_sku', models.ForeignKey(blank=True, help_text='SKU especifico con talla. Nullable para backward compat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediente_lines', to='brands.brandsku')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='expedientes.expediente')),
                ('pricelist_used', models.ForeignKey(blank=True, help_text='Snapshot de la lista de precios usada al crear la linea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lines_snapshot', to='pricing.pricelist')),
                ('product', models.ForeignKey(help_text='SKU from ProductMaster', on_delete=django.db.models.deletion.PROTECT, related_name='expediente_lines', to='productos.productmaster')),
                ('separated_to_expediente', models.ForeignKey(blank=True, help_text='Expediente destino si esta linea fue separada (split)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_lines', to='expedientes.expediente')),
                ('factory_order', models.ForeignKey(blank=True, help_text='Orden de fabrica a la que pertenece esta linea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lines', to='expedientes.factoryorder')),
            ],
            options={
                'verbose_name': 'Expediente Product Line',
                'verbose_name_plural': 'Expediente Product Lines',
                'ordering': ['created_at'],
            },
        ),
    ]
