# Generated by Django 5.1.5 on 2026-04-01 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandconfigversion_catalogversion'),
        ('expedientes', '0019_s20_proforma_fks'),
        ('productos', '0003_productmaster_productvariant'),
        ('users', '0005_mwtuser_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_seen_event_id', models.BigIntegerField(default=0, help_text='ID del último EventLog visto. 0 = nunca visto. Avanza al max(id) del queryset base al llamar mark-seen.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Notification State',
                'verbose_name_plural': 'User Notification States',
            },
        ),
        migrations.AddField(
            model_name='eventlog',
            name='action_source',
            field=models.CharField(blank=True, help_text='S21: Origen del comando. Contrato cerrado: C1..C22, create_proforma, reassign_line, change_mode, patch_{estado}, system_*.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='proforma',
            field=models.ForeignKey(blank=True, help_text='S21: Proforma (ART-02) relacionada con el evento. NULL si no aplica.', limit_choices_to={'artifact_type': 'ART-02'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='expedientes.artifactinstance'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='S21: Usuario que disparó el evento. NULL para eventos de sistema/Celery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expediente',
            name='custom_artifact_policy',
            field=models.JSONField(blank=True, default=dict, help_text='S21: Overrides de política de artefactos específicos de este expediente. Estructura: {"ESTADO": {"add": ["ART-XX"], "remove": ["ART-YY"]}}. Solo modificable por superusers vía Admin Panel.'),
        ),
        migrations.AlterField(
            model_name='costline',
            name='amount_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='costline',
            name='base_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='costline',
            name='cost_behavior',
            field=models.CharField(blank=True, choices=[('fixed_per_operation', 'Fixed per Operation'), ('variable_per_unit', 'Variable per Unit'), ('variable_per_weight', 'Variable per Weight'), ('semi_variable', 'Semi-Variable')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='costline',
            name='cost_category',
            field=models.CharField(choices=[('landed_cost', 'Landed Cost'), ('tax_credit', 'Tax Credit (recuperable)'), ('recoverable', 'Recoverable (otro)'), ('non_deductible', 'Non-Deductible')], default='landed_cost', max_length=20),
        ),
        migrations.AlterField(
            model_name='costline',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='costline',
            name='visibility',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('CLIENT', 'Client')], default='INTERNAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='airline_or_shipping_company',
            field=models.CharField(blank=True, help_text='Nombre de la aerolínea o naviera utilizada', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='arrival_location',
            field=models.CharField(blank=True, help_text='Puerto o aeropuerto de llegada del envío', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='awb_bl_number',
            field=models.CharField(blank=True, help_text='Número Air Waybill (aéreo) o Bill of Lading (marítimo)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cargo_manager',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('FABRICA', 'Fábrica')], help_text='Quién gestiona la carga y envío', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_days_client',
            field=models.IntegerField(blank=True, help_text='Días de crédito acordados con el cliente', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_days_mwt',
            field=models.IntegerField(blank=True, help_text='Días de crédito acordados con MWT', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_limit_client',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del límite de crédito del cliente (DEC-EXP-03) al momento de creación', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='credit_limit_mwt',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot del límite de crédito MWT (DEC-EXP-03) al momento de creación', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='dispatch_additional_info',
            field=models.TextField(blank=True, help_text='Información adicional libre sobre el despacho', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fabrication_end_date',
            field=models.DateField(blank=True, help_text='Fecha de fin de fabricación', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fabrication_start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de fabricación', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='factory_order_number',
            field=models.CharField(blank=True, help_text='Número de orden en sistema del fabricante (DEC-EXP-01). Campo flat para queries rápidos; detalle en FactoryOrder.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='invoice_client_number',
            field=models.CharField(blank=True, help_text='Número de factura emitida al cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='invoice_mwt_number',
            field=models.CharField(blank=True, help_text='Número de factura interna MWT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='master_expediente',
            field=models.ForeignKey(blank=True, help_text='Expediente master cuando éste fue fusionado (DEC-EXP-02). El merge lo decide el CEO manualmente en Sprint 18.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_followers', to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='operado_por',
            field=models.CharField(blank=True, choices=[('CLIENTE', 'Cliente'), ('MWT', 'Muito Work Limitada')], help_text='Quién opera logísticamente este expediente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='origin_location',
            field=models.CharField(blank=True, help_text='Puerto o aeropuerto de origen del envío', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='proforma_client_number',
            field=models.CharField(blank=True, help_text='Número de proforma emitida al cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='proforma_mwt_number',
            field=models.CharField(blank=True, help_text='Número de proforma emitida a MWT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Número de orden de compra del cliente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='ref_number',
            field=models.CharField(blank=True, help_text='Número de referencia interna del expediente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='shipping_method',
            field=models.CharField(blank=True, help_text='Método de envío (aéreo, marítimo, terrestre, courier)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='shipping_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del flete de envío', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='transit_arrival_date',
            field=models.DateField(blank=True, help_text='Fecha estimada o real de llegada en tránsito', null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='url_cotizacion_envio',
            field=models.URLField(blank=True, help_text='URL de la cotización de envío', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='credit_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='metodo_pago',
            field=models.CharField(choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('NOTA_CREDITO', 'Nota de Crédito')], max_length=30),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='tipo_pago',
            field=models.CharField(choices=[('COMPLETO', 'Pago Completo'), ('PARCIAL', 'Pago Parcial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expedientepago',
            name='url_comprobante',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='brand_sku',
            field=models.ForeignKey(blank=True, help_text='SKU específico con talla. Nullable para backward compat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediente_lines', to='brands.brandsku'),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='factory_order',
            field=models.ForeignKey(blank=True, help_text='Orden de fábrica a la que pertenece esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lines', to='expedientes.factoryorder'),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='modification_reason',
            field=models.CharField(blank=True, help_text='Razón del cambio de cantidad o precio', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='price_source',
            field=models.CharField(choices=[('pricelist', 'Lista de precios activa'), ('manual', 'Ingresado manualmente'), ('override', 'Override por expediente')], default='manual', help_text='Origen del precio: lista activa, manual, u override CEO', max_length=30),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='product',
            field=models.ForeignKey(help_text='SKU from ProductMaster — never free text', on_delete=django.db.models.deletion.PROTECT, related_name='expediente_lines', to='productos.productmaster'),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='proforma',
            field=models.ForeignKey(blank=True, help_text='S20-01: Proforma (ART-02) a la que pertenece esta línea. NULL en líneas legacy pre-S20.', limit_choices_to={'artifact_type': 'ART-02'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_lines', to='expedientes.artifactinstance'),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='quantity_modified',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad modificada post-creación (si aplica)', null=True),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='separated_to_expediente',
            field=models.ForeignKey(blank=True, help_text='Expediente destino si esta línea fue separada (split)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_lines', to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario editable por expediente. Inicializado desde resolve_client_price() si disponible.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='expedienteproductline',
            name='unit_price_modified',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio modificado post-creación (si aplica)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='factoryorder',
            name='order_number',
            field=models.CharField(help_text='Número en sistema del fabricante', max_length=100),
        ),
        migrations.AlterField(
            model_name='factoryorder',
            name='purchase_number',
            field=models.CharField(blank=True, help_text='Número de orden de compra al fabricante', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentline',
            name='method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentline',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['aggregate_id', '-event_id'], name='idx_eventlog_exp_id_desc'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['proforma', '-event_id'], name='idx_eventlog_pf_id_desc'),
        ),
    ]
