# Generated by Django 5.1.5 on 2026-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0020_usernotificationstate_eventlog_action_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationstate',
            name='last_seen_event_id',
        ),
        migrations.AddField(
            model_name='usernotificationstate',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp del último EventLog visto. NULL = nunca visto. Se actualiza en mark-seen.', null=True),
        ),
    ]
