# Generated by Django 5.1.5 on 2026-04-01 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0021_remove_usernotificationstate_last_seen_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='expediente',
            field=models.ForeignKey(blank=True, help_text='S21: Expediente relacionado con el evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='proforma',
            field=models.ForeignKey(blank=True, help_text='S21: Proforma (ART-02) relacionada con el evento. NULL si no aplica.', limit_choices_to={'artifact_type': 'ART-02'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs_proforma', to='expedientes.artifactinstance'),
        ),
    ]
