# Generated by Django 5.1.5 on 2026-03-22 20:06

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_brandconfigversion_catalogversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandClientAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('incoterm', models.CharField(blank=True, max_length=10, null=True)),
                ('party_type', models.CharField(choices=[('group', 'Group'), ('subsidiary', 'Subsidiary')], max_length=20)),
                ('party_id', models.IntegerField()),
                ('version', models.CharField(max_length=20)),
                ('max_order_revisions', models.IntegerField(blank=True, null=True)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_brandclientagreement',
            },
        ),
        migrations.CreateModel(
            name='BrandClientPriceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('group', 'Group'), ('subsidiary', 'Subsidiary')], max_length=20)),
                ('party_id', models.IntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('override_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_brandclientpriceagreement',
            },
        ),
        migrations.CreateModel(
            name='BrandSupplierAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_id', models.IntegerField()),
                ('version', models.CharField(max_length=20)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_brandsupplieragreement',
            },
        ),
        migrations.CreateModel(
            name='BrandWorkflowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_policies', to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_brandworkflowpolicy',
            },
        ),
        migrations.CreateModel(
            name='ArtifactRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_requirements', to='agreements.brandworkflowpolicy')),
            ],
            options={
                'db_table': 'agreements_artifactrequirement',
            },
        ),
        migrations.CreateModel(
            name='CommandPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_policies', to='agreements.brandworkflowpolicy')),
            ],
            options={
                'db_table': 'agreements_commandpolicy',
            },
        ),
        migrations.CreateModel(
            name='CreditPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(max_length=50)),
                ('subject_type', models.CharField(max_length=50)),
                ('subject_id', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_creditpolicy',
            },
        ),
        migrations.CreateModel(
            name='CreditExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_exposure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to='agreements.creditpolicy')),
            ],
            options={
                'db_table': 'agreements_creditexposure',
            },
        ),
        migrations.CreateModel(
            name='PaymentTermPricingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('agreement', 'Agreement'), ('brand_default', 'Brand Default')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agreements.brandclientagreement')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_paymenttermpricingversion',
            },
        ),
        migrations.CreateModel(
            name='PaymentTermPricingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_days', models.IntegerField()),
                ('price_index', models.DecimalField(decimal_places=6, max_digits=8)),
                ('label', models.CharField(max_length=50)),
                ('pricing_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='agreements.paymenttermpricingversion')),
            ],
            options={
                'db_table': 'agreements_paymenttermpricingterm',
            },
        ),
        migrations.CreateModel(
            name='StatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_policies', to='agreements.brandworkflowpolicy')),
            ],
            options={
                'db_table': 'agreements_statepolicy',
            },
        ),
        migrations.CreateModel(
            name='TransitionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=50)),
                ('to_state', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=50)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_policies', to='agreements.brandworkflowpolicy')),
            ],
            options={
                'db_table': 'agreements_transitionpolicy',
            },
        ),
        migrations.CreateModel(
            name='AssortmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('group', 'Group'), ('subsidiary', 'Subsidiary')], max_length=20)),
                ('party_id', models.IntegerField()),
                ('channel', models.CharField(max_length=50)),
                ('include_rules', models.JSONField(default=list)),
                ('exclude_rules', models.JSONField(default=list)),
                ('valid_daterange', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
            options={
                'db_table': 'agreements_assortmentpolicy',
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('brand', '='), ('party_type', '='), ('party_id', '='), ('channel', '='), ('valid_daterange', '&&')], name='exclude_overlapping_assortment')],
            },
        ),
        migrations.AddConstraint(
            model_name='brandclientagreement',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('brand', '='), ('party_type', '='), ('party_id', '='), ('valid_daterange', '&&')], name='exclude_overlapping_agreements'),
        ),
        migrations.AddConstraint(
            model_name='brandclientpriceagreement',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('brand', '='), ('party_type', '='), ('party_id', '='), ('sku', '='), ('mode', '='), ('currency', '='), ('valid_daterange', '&&')], name='exclude_overlapping_price_agreements'),
        ),
        migrations.AddConstraint(
            model_name='brandworkflowpolicy',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('brand', '='), ('valid_daterange', '&&')], name='exclude_overlapping_workflow_policy'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactrequirement',
            unique_together={('policy', 'artifact_type')},
        ),
        migrations.AlterUniqueTogether(
            name='commandpolicy',
            unique_together={('policy', 'command')},
        ),
        migrations.AddConstraint(
            model_name='creditpolicy',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('scope_type', '='), ('subject_type', '='), ('subject_id', '='), ('brand', '='), ('currency', '='), ('valid_daterange', '&&')], name='exclude_overlapping_credit'),
        ),
        migrations.AddConstraint(
            model_name='paymenttermpricingversion',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'active')), expressions=[('brand', '='), ('scope_type', '='), ('agreement', '='), ('valid_daterange', '&&')], name='exclude_overlapping_paymentterm'),
        ),
        migrations.AlterUniqueTogether(
            name='paymenttermpricingterm',
            unique_together={('pricing_version', 'payment_days')},
        ),
        migrations.AlterUniqueTogether(
            name='statepolicy',
            unique_together={('policy', 'state')},
        ),
        migrations.AlterUniqueTogether(
            name='transitionpolicy',
            unique_together={('policy', 'from_state', 'to_state', 'command')},
        ),
    ]
