# Generated by Django 5.2.11 on 2026-03-24 15:14

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        ('expedientes', '0015_expediente_credit_blocked_expediente_credit_warning'),
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditexposure',
            name='reserved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='CreditOverride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_code', models.CharField(help_text='Command authorized: C1, C6, C8, C9, C14', max_length=10)),
                ('amount_over_limit', models.DecimalField(decimal_places=2, help_text='Amount exceeding credit limit at time of authorization', max_digits=14)),
                ('reason', models.TextField(help_text='Minimum 10 characters')),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(help_text='Must be CEO (is_superuser=True)', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brands.brand')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_overrides', to='expedientes.expediente')),
            ],
            options={
                'db_table': 'agreements_creditoverride',
                'unique_together': {('expediente', 'command_code')},
            },
        ),
    ]
