# Generated by Django 5.2.11 on 2026-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_creditexposure_reserved_amount_creditoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandclientagreement',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='brandclientagreement',
            name='standard_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
