# Generated by Django 5.2.11 on 2026-03-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientgroup_clientultimateparent_clientsubsidiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsubsidiary',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientsubsidiary',
            name='email_billing',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientsubsidiary',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientsubsidiary',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
