# Generated by Django 5.2.11 on 2026-03-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brandconfigversion_catalogversion'),
        ('productos', '0002_alter_producto_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_base', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hs_code', models.CharField(blank=True, max_length=50)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cbm', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('moq', models.IntegerField(default=1)),
                ('country_eligibility', models.JSONField(default=list)),
                ('channel_eligibility', models.JSONField(default=list)),
                ('uom', models.CharField(default='PAIR', max_length=20)),
                ('country_of_origin', models.CharField(blank=True, max_length=3)),
                ('lead_time_days', models.IntegerField(default=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_masters', to='brands.brand')),
            ],
            options={
                'db_table': 'productos_productmaster',
                'ordering': ['sku_base'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_sku', models.CharField(max_length=100, unique=True)),
                ('attributes', models.JSONField(default=dict)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='productos.productmaster')),
            ],
            options={
                'db_table': 'productos_productvariant',
            },
        ),
    ]
