# Generated by Django 5.2.11 on 2026-03-06 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand_type', models.CharField(choices=[('own', 'Own'), ('client', 'Client')], default='client', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_key', models.CharField(max_length=3)),
                ('arch', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HGH', 'High')], max_length=3)),
                ('size', models.CharField(max_length=10)),
                ('sku_code', models.CharField(max_length=50, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='brands.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandArtifactRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(max_length=20)),
                ('destination', models.CharField(choices=[('CR', 'Costa Rica'), ('USA', 'United States'), ('ALL', 'All destinations')], default='ALL', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_rules', to='brands.brand')),
            ],
            options={
                'unique_together': {('brand', 'artifact_type', 'destination')},
            },
        ),
    ]
