# Generated by Django 5.2.11 on 2026-03-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_alter_producto_created_at'),
        ('transfers', '0002_retarget_legalentity_fks_to_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('received_at', models.DateTimeField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='transfers.node')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_entries', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'db_table': 'inventario_inventoryentry',
                'ordering': ['-received_at'],
                'unique_together': {('product', 'node', 'lot_number')},
            },
        ),
    ]
