# Generated by Django 5.2.11 on 2026-03-06 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=10, unique=True)),
                ('product_slug', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('destination_template', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('fallback_url', models.URLField(default='https://ranawalk.com')),
                ('override_url', models.URLField(blank=True, null=True)),
                ('override_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_lang', models.CharField(max_length=2)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_hash', models.CharField(max_length=32)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qr.qrroute')),
            ],
        ),
    ]
