# Generated by Django 5.1.5 on 2026-03-04 01:53
# NOTE: DB FKs point to expedientes_legalentity at creation time.
# State uses expedientes.legalentity to avoid circular dep with expedientes/0005.
# FKs are retargeted to core.legalentity in transfers/0002.
import apps.transfers.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0004_alter_eventlog_aggregate_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('node_type', models.CharField(choices=[('fiscal', 'Fiscal'), ('owned_warehouse', 'Owned Warehouse'), ('fba', 'FBA'), ('third_party', 'Third Party'), ('factory', 'Factory')], max_length=30)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='expedientes.legalentity')),
            ],
            options={
                'verbose_name': 'Node',
                'db_table': 'transfers_node',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(default=apps.transfers.models.generate_transfer_id, editable=False, max_length=30, unique=True)),
                ('ownership_changes', models.BooleanField(default=False)),
                ('legal_context', models.CharField(choices=[('internal', 'Internal'), ('nationalization', 'Nationalization'), ('reexport', 'Reexport'), ('distribution', 'Distribution'), ('consignment', 'Consignment')], max_length=30)),
                ('customs_required', models.BooleanField(default=False)),
                ('pricing_context', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('exception_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='transfers.node')),
                ('ownership_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_ownership_after', to='expedientes.legalentity')),
                ('ownership_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_ownership_before', to='expedientes.legalentity')),
                ('source_expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='expedientes.expediente')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='transfers.node')),
            ],
            options={
                'db_table': 'transfers_transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('quantity_dispatched', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('partial', 'Partial')], max_length=20, null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transfer')),
            ],
            options={
                'db_table': 'transfers_transferline',
            },
        ),
    ]
